import { renderNotice, renderPanel, renderProcessing, renderTimeline, renderWorkbench } from "/assets/workbench_ui.mjs";

export function createRendering(c) {
  const { app, state } = c;
  function replaceMarkup(target, markup) { const body = new DOMParser().parseFromString(markup, "text/html").body; target.replaceChildren(...body.childNodes); }
  function renderFatalState(error) { const main = document.createElement("main"); main.className = "fatal-state"; main.setAttribute("role", "alert"); const kicker = document.createElement("p"); kicker.className = "kicker"; kicker.textContent = "Local project unavailable"; const title = document.createElement("h1"); title.textContent = "The workbench could not open"; const detail = document.createElement("p"); detail.textContent = error?.message || "An unknown local error occurred."; const retry = document.createElement("button"); retry.className = "primary-button"; retry.dataset.action = "reload"; retry.textContent = "Try again"; main.append(kicker, title, detail, retry); app.replaceChildren(main); }
  function setNotice(message, kind = "info") { state.notice = message ? { message, kind } : null; const region = app.querySelector("[data-notice-region]"); if (region) replaceMarkup(region, renderNotice(state.notice)); }
  function setBusy(key, busy) { if (busy) state.busy.add(key); else state.busy.delete(key); app.querySelectorAll(`[data-busy-key="${CSS.escape(key)}"]`).forEach((button) => { button.disabled = busy; button.setAttribute("aria-busy", String(busy)); }); }
  async function runMutation(key, activity, operation) { if (state.busy.has(key)) return false; setBusy(key, true); setNotice(`${activity}…`, "info"); try { await operation(); return true; } catch (error) { if (error.status === 409) { await c.load({ preservePlayback: true, quiet: true }).catch(() => undefined); setNotice("The project changed in another action. The latest local version is shown; please try again.", "error"); } else setNotice(`${activity} could not be completed: ${error.message}`, "error"); return false; } finally { setBusy(key, false); } }
  function render(restore = null) { replaceMarkup(app, renderWorkbench(state)); c.bindMedia(restore); c.openRenderedDialog(); if (state.pendingFocus) { const target = app.querySelector(`[data-review-card="${CSS.escape(state.pendingFocus)}"]`); state.pendingFocus = ""; target?.focus(); } }
  function renderPreservingPlayback() { render(c.snapshotPlayback()); }
  function refreshPanel() { const panel = app.querySelector("[data-workspace-panel]"); if (panel) replaceMarkup(panel, renderPanel(state)); app.querySelectorAll("[data-tab]").forEach((tab) => { const selected = tab.dataset.tab === state.activePanel; if (tab.getAttribute("role") === "tab") { tab.setAttribute("aria-selected", String(selected)); tab.tabIndex = selected ? 0 : -1; } }); }
  function refreshTimeline() { const root = app.querySelector("[data-timeline-root]"); if (root) replaceMarkup(root, renderTimeline(state)); c.syncPlayback(); }
  function refreshProcessing() { const section = app.querySelector(".processing-section"); if (!section) return; const body = new DOMParser().parseFromString(renderProcessing(state), "text/html").body; section.replaceWith(...body.childNodes); }
  function selectPanel(name, focus = false) { if (!["review", "transcript", "lesson"].includes(name)) return; state.activePanel = name; refreshPanel(); if (focus) app.querySelector(`[data-tab="${name}"][role="tab"]`)?.focus(); }
  return { renderFatalState, setNotice, setBusy, runMutation, render, renderPreservingPlayback, refreshPanel, refreshTimeline, refreshProcessing, selectPanel };
}
