"""Typed lesson-recall projections derived from validated evidence."""

from notewitness.core.lesson.model import (
    ActivityKind,
    ActivitySegment,
    ActivityStatistic,
    EvidenceExcerpt,
    EvidenceTopic,
    FullTranscriptEntry,
    LessonNotes,
    LessonProgress,
    LessonStatistics,
    LessonSummary,
    NamedCount,
    PedagogicalMoment,
    PlaybackBookmark,
    PracticePlan,
    PracticeTask,
    RecordRevisionLink,
    SourceGraphProvenance,
    SourceReference,
    TimelineExtent,
    TranscriptTurn,
    text_body,
)


__all__ = (
    "ActivityKind",
    "ActivitySegment",
    "ActivityStatistic",
    "EvidenceExcerpt",
    "EvidenceTopic",
    "FullTranscriptEntry",
    "LessonNotes",
    "LessonProgress",
    "LessonStatistics",
    "LessonSummary",
    "NamedCount",
    "PedagogicalMoment",
    "PlaybackBookmark",
    "PracticePlan",
    "PracticeTask",
    "RecordRevisionLink",
    "SourceGraphProvenance",
    "SourceReference",
    "TimelineExtent",
    "TranscriptTurn",
    "text_body",
)
